using UnityEngine;
using UnityEngine.UI;
using UnityEngine.SceneManagement;
using System.Collections;

public class MarcadorHUD : MonoBehaviour
{
    public static MarcadorHUD Instancia { get; private set; }

    [Header("Configuración del Partido")]
    [Tooltip("Duración del partido en segundos reales")]
    public float duracionPartido = 90f;
    
    [Header("Referencias de UI (Opcional - Se autogeneran si están vacías)")]
    public Canvas canvasHUD;
    public Text textoTiempo;
    public Text textoGoles;
    public Text textoNoqueos;
    public Text textoAnuncios;
    public GameObject panelFinPartido;
    public Text textoResumenFin;
    public Button botonReiniciar;

    // Estadísticas
    private float tiempoRestante;
    private int golesActuales = 0;
    private int noqueosActuales = 0;
    private int tacleadasSufridas = 0;
    private bool partidoTerminado = false;

    // Control de animación del anuncio
    private Coroutine corutinaAnuncio;

    [RuntimeInitializeOnLoadMethod(RuntimeInitializeLoadType.BeforeSceneLoad)]
    private static void InicializarEscuchaEscenas()
    {
        SceneManager.sceneLoaded -= OnSceneLoaded;
        SceneManager.sceneLoaded += OnSceneLoaded;
    }

    private static void OnSceneLoaded(Scene scene, LoadSceneMode mode)
    {
        // No autogenerar el marcador si estamos en el menú principal
        if (scene.name == "MainMenu")
        {
            return;
        }

        if (Instancia == null)
        {
            MarcadorHUD hudExistente = FindFirstObjectByType<MarcadorHUD>();
            if (hudExistente == null)
            {
                GameObject go = new GameObject("MarcadorHUD_AutoGenerated");
                go.AddComponent<MarcadorHUD>();
                Debug.Log("¡Se autogeneró el MarcadorHUD al cargar la escena: " + scene.name + "!");
            }
        }
    }

    void Awake()
    {
        if (Instancia != null && Instancia != this)
        {
            Destroy(gameObject);
            return;
        }
        Instancia = this;
        tiempoRestante = duracionPartido;
    }

    void Start()
    {
        // Desactivar la UI vieja redundante si existe
        GameObject viejoCanvas = GameObject.Find("CanvasFutbol");
        if (viejoCanvas != null)
        {
            viejoCanvas.SetActive(false);
        }

        // Si no se han asignado las referencias, construir la UI dinámicamente
        if (canvasHUD == null)
        {
            ConstruirUIDinamica();
        }

        // Asegurar que exista un EventSystem en la escena para procesar clicks en la UI
        UnityEngine.EventSystems.EventSystem existingEventSystem = FindFirstObjectByType<UnityEngine.EventSystems.EventSystem>();
        if (existingEventSystem == null)
        {
            GameObject eventSystemObj = new GameObject("EventSystem");
            eventSystemObj.AddComponent<UnityEngine.EventSystems.EventSystem>();
            eventSystemObj.AddComponent<UnityEngine.InputSystem.UI.InputSystemUIInputModule>();
            Debug.Log("¡Se autogeneró el EventSystem con InputSystemUIInputModule para compatibilidad con el nuevo Input System!");
        }
        else
        {
            // Si ya existe un EventSystem, nos aseguramos de que use el nuevo módulo de Input System
            // para evitar el crash con UnityEngine.Input
            UnityEngine.EventSystems.StandaloneInputModule oldModule = existingEventSystem.GetComponent<UnityEngine.EventSystems.StandaloneInputModule>();
            if (oldModule != null)
            {
                Destroy(oldModule);
                existingEventSystem.gameObject.AddComponent<UnityEngine.InputSystem.UI.InputSystemUIInputModule>();
                Debug.Log("¡Se reemplazó StandaloneInputModule por InputSystemUIInputModule para compatibilidad con el nuevo Input System!");
            }
        }
        
        ActualizarTextoMarcador();
        MostrarAnuncio("¡EMPIEZA EL PARTIDO!", Color.yellow);
    }

    void Update()
    {
        if (partidoTerminado) return;

        // Decrementar temporizador
        tiempoRestante -= Time.deltaTime;
        if (tiempoRestante <= 0f)
        {
            tiempoRestante = 0f;
            FinalizarPartido();
        }

        ActualizarTextoTiempo();
    }

    private void ActualizarTextoTiempo()
    {
        if (textoTiempo != null)
        {
            int minutos = Mathf.FloorToInt(tiempoRestante / 60f);
            int segundos = Mathf.FloorToInt(tiempoRestante % 60f);
            textoTiempo.text = "⏱️ " + string.Format("{0:00}:{1:00}", minutos, segundos);
            
            // Si queda poco tiempo (menos de 15s), poner en rojo parpadeante
            if (tiempoRestante < 15f && tiempoRestante > 0f)
            {
                textoTiempo.color = Mathf.PingPong(Time.time * 4f, 1f) > 0.5f ? Color.red : Color.white;
            }
        }
    }

    private void ActualizarTextoMarcador()
    {
        if (textoGoles != null)
        {
            textoGoles.text = "⚽ GOLES: " + golesActuales;
        }
        if (textoNoqueos != null)
        {
            textoNoqueos.text = "💀 K.O.: " + noqueosActuales;
        }
    }

    // --- MÉTODOS DE EVENTOS DE GAMEPLAY ---

    public void RegistrarGol()
    {
        if (partidoTerminado) return;
        golesActuales++;
        ActualizarMarcadorYAnunciar("¡GOLAZO!", new Color(0.0f, 1.0f, 0.9f)); // Cian brillante
    }

    public void RegistrarNoqueo(string nombreEnemigo)
    {
        if (partidoTerminado) return;
        noqueosActuales++;
        ActualizarMarcadorYAnunciar("¡K.O. A " + nombreEnemigo.ToUpper() + "!", Color.red);
    }

    public void RegistrarTacleado()
    {
        if (partidoTerminado) return;
        tacleadasSufridas++;
        MostrarAnuncio("¡BARRIDA SUFRIDA!", new Color(1f, 0.5f, 0f)); // Naranja
    }

    private void ActualizarMarcadorYAnunciar(string mensaje, Color color)
    {
        ActualizarTextoMarcador();
        
        // Si hay una pantalla con texto de gol en ArcoDeFutbol, desactivarla o integrarla para evitar doble cartel
        ArcoDeFutbol arco = FindObjectOfType<ArcoDeFutbol>();
        if (arco != null && arco.panelGolUI != null)
        {
            arco.panelGolUI.SetActive(false); // Ocultar el panel antiguo para usar nuestro anuncio premium unificado
        }

        MostrarAnuncio(mensaje, color);
    }

    public void MostrarAnuncio(string mensaje, Color color)
    {
        if (textoAnuncios == null) return;
        
        if (corutinaAnuncio != null)
        {
            StopCoroutine(corutinaAnuncio);
        }
        corutinaAnuncio = StartCoroutine(AnimarAnuncio(mensaje, color));
    }

    private IEnumerator AnimarAnuncio(string mensaje, Color color)
    {
        textoAnuncios.text = mensaje;
        textoAnuncios.color = color;
        textoAnuncios.gameObject.SetActive(true);

        RectTransform rect = textoAnuncios.GetComponent<RectTransform>();
        
        // Fase 1: Pop-in rápido con aumento de tamaño (zoom)
        float t = 0f;
        float duracionPop = 0.25f;
        while (t < 1f)
        {
            t += Time.unscaledDeltaTime / duracionPop;
            float escala = Mathf.Lerp(0.3f, 1.4f, Mathf.Sin(t * Mathf.PI * 0.5f));
            rect.localScale = new Vector3(escala, escala, escala);
            yield return null;
        }

        // Estabilizar a escala 1.2
        rect.localScale = new Vector3(1.2f, 1.2f, 1.2f);
        
        // Esperar visible
        yield return new WaitForSecondsRealtime(1.2f);

        // Fase 2: Fade-out y encogimiento leve
        t = 0f;
        float duracionFade = 0.4f;
        Color colorInicial = color;
        while (t < 1f)
        {
            t += Time.unscaledDeltaTime / duracionFade;
            float alfa = Mathf.Lerp(1f, 0f, t);
            textoAnuncios.color = new Color(colorInicial.r, colorInicial.g, colorInicial.b, alfa);
            float escala = Mathf.Lerp(1.2f, 0.9f, t);
            rect.localScale = new Vector3(escala, escala, escala);
            yield return null;
        }

        textoAnuncios.gameObject.SetActive(false);
    }

    // --- FIN DEL PARTIDO Y REINICIO ---

    private void FinalizarPartido()
    {
        partidoTerminado = true;
        
        // Pausar juego
        Time.timeScale = 0f;
        
        // Mostrar cursor
        Cursor.lockState = CursorLockMode.None;
        Cursor.visible = true;

        if (panelFinPartido != null)
        {
            panelFinPartido.SetActive(true);
        }

        // Calcular calificación del partido (S, A, B, C, D)
        string calificacion = "D";
        string colorCalificacion = "#ff3333"; // Rojo

        if (golesActuales >= 5 && noqueosActuales >= 3)
        {
            calificacion = "S";
            colorCalificacion = "#ffd700"; // Dorado
        }
        else if (golesActuales >= 3 && noqueosActuales >= 2)
        {
            calificacion = "A";
            colorCalificacion = "#ff8800"; // Naranja
        }
        else if (golesActuales >= 2)
        {
            calificacion = "B";
            colorCalificacion = "#33ff33"; // Verde
        }
        else if (golesActuales >= 1)
        {
            calificacion = "C";
            colorCalificacion = "#33aaff"; // Azul
        }

        if (textoResumenFin != null)
        {
            textoResumenFin.text = string.Format(
                "⚽  <b>GOLES ANOTADOS:</b> <color=#33ff33>{0}</color>\n\n" +
                "💀  <b>DEFENSORES NOQUEADOS:</b> <color=#ff3333>{1}</color>\n\n" +
                "🛡️  <b>BARRIDAS SUFRIDAS:</b> <color=#ff8800>{2}</color>\n\n\n" +
                "🏆  <b>RANGO DEL PARTIDO:</b> <color={3}><b><size=65>{4}</size></b></color>",
                golesActuales,
                noqueosActuales,
                tacleadasSufridas,
                colorCalificacion,
                calificacion
            );
        }

        MostrarAnuncio("¡FIN DEL PARTIDO!", Color.yellow);
    }

    public void RecomenzarPartido()
    {
        Debug.Log("Reiniciando partido...");
        Time.timeScale = 1f;
        SceneManager.LoadScene(SceneManager.GetActiveScene().name);
    }

    public void SalirDelJuego()
    {
        Debug.Log("Volviendo al Menú Principal...");
        Time.timeScale = 1f;
        Cursor.lockState = CursorLockMode.None;
        Cursor.visible = true;
        SceneManager.LoadScene("MainMenu");
    }

    // --- CONSTRUCCIÓN DINÁMICA DE LA UI ---

    private void ConstruirUIDinamica()
    {
        // 1. Crear Canvas Principal
        GameObject goCanvas = new GameObject("HUD_Canvas");
        canvasHUD = goCanvas.AddComponent<Canvas>();
        canvasHUD.renderMode = RenderMode.ScreenSpaceOverlay;
        canvasHUD.sortingOrder = 10;
        
        CanvasScaler scaler = goCanvas.AddComponent<CanvasScaler>();
        scaler.uiScaleMode = CanvasScaler.ScaleMode.ScaleWithScreenSize;
        scaler.referenceResolution = new Vector2(1920, 1080);
        
        goCanvas.AddComponent<GraphicRaycaster>();
        
        // 2. Panel superior del Marcador (Estilo Glassmorphism Premium)
        GameObject goPanel = new GameObject("PanelMarcador");
        goPanel.transform.SetParent(goCanvas.transform, false);
        
        RectTransform rtPanel = goPanel.AddComponent<RectTransform>();
        rtPanel.anchorMin = new Vector2(0.5f, 1f);
        rtPanel.anchorMax = new Vector2(0.5f, 1f);
        rtPanel.pivot = new Vector2(0.5f, 1f);
        rtPanel.anchoredPosition = new Vector2(0f, -15f);
        rtPanel.sizeDelta = new Vector2(580f, 75f);
        
        Image imgPanel = goPanel.AddComponent<Image>();
        imgPanel.color = new Color(0.04f, 0.04f, 0.07f, 0.85f); // Gris azulado ultra oscuro traslúcido
        
        // Bordes con Outline neón moderno en el panel
        Outline panelOutline = goPanel.AddComponent<Outline>();
        panelOutline.effectColor = new Color(0.0f, 0.8f, 1.0f, 0.8f); // Cyan neón
        panelOutline.effectDistance = new Vector2(2f, 2f);

        // 3. Texto del Temporizador (En el centro del panel)
        GameObject goTiempo = new GameObject("TextoTiempo");
        goTiempo.transform.SetParent(goPanel.transform, false);
        textoTiempo = goTiempo.AddComponent<Text>();
        textoTiempo.font = Resources.GetBuiltinResource<Font>("LegacyRuntime.ttf");
        textoTiempo.fontSize = 28;
        textoTiempo.alignment = TextAnchor.MiddleCenter;
        textoTiempo.color = Color.white;
        
        RectTransform rtTiempo = goTiempo.GetComponent<RectTransform>();
        rtTiempo.anchorMin = new Vector2(0.5f, 0.5f);
        rtTiempo.anchorMax = new Vector2(0.5f, 0.5f);
        rtTiempo.anchoredPosition = Vector2.zero;
        rtTiempo.sizeDelta = new Vector2(160f, 60f);

        // Contorno más fuerte para legibilidad
        Outline outlineTiempo = goTiempo.AddComponent<Outline>();
        outlineTiempo.effectColor = Color.black;
        outlineTiempo.effectDistance = new Vector2(1.5f, 1.5f);

        // 4. Texto de Goles (Lado izquierdo del panel)
        GameObject goGoles = new GameObject("TextoGoles");
        goGoles.transform.SetParent(goPanel.transform, false);
        textoGoles = goGoles.AddComponent<Text>();
        textoGoles.font = Resources.GetBuiltinResource<Font>("LegacyRuntime.ttf");
        textoGoles.fontSize = 24;
        textoGoles.alignment = TextAnchor.MiddleLeft;
        textoGoles.color = new Color(0.2f, 1f, 0.4f); // Verde neón
        
        RectTransform rtGoles = goGoles.GetComponent<RectTransform>();
        rtGoles.anchorMin = new Vector2(0f, 0.5f);
        rtGoles.anchorMax = new Vector2(0f, 0.5f);
        rtGoles.pivot = new Vector2(0f, 0.5f);
        rtGoles.anchoredPosition = new Vector2(25f, 0f);
        rtGoles.sizeDelta = new Vector2(180f, 50f);

        Outline outlineGoles = goGoles.AddComponent<Outline>();
        outlineGoles.effectColor = Color.black;
        outlineGoles.effectDistance = new Vector2(1.5f, 1.5f);

        // 5. Texto de Noqueos (Lado derecho del panel)
        GameObject goNoqueos = new GameObject("TextoNoqueos");
        goNoqueos.transform.SetParent(goPanel.transform, false);
        textoNoqueos = goNoqueos.AddComponent<Text>();
        textoNoqueos.font = Resources.GetBuiltinResource<Font>("LegacyRuntime.ttf");
        textoNoqueos.fontSize = 24;
        textoNoqueos.alignment = TextAnchor.MiddleRight;
        textoNoqueos.color = new Color(1f, 0.2f, 0.2f); // Rojo neón
        
        RectTransform rtNoqueos = goNoqueos.GetComponent<RectTransform>();
        rtNoqueos.anchorMin = new Vector2(1f, 0.5f);
        rtNoqueos.anchorMax = new Vector2(1f, 0.5f);
        rtNoqueos.pivot = new Vector2(1f, 0.5f);
        rtNoqueos.anchoredPosition = new Vector2(-25f, 0f);
        rtNoqueos.sizeDelta = new Vector2(180f, 50f);

        Outline outlineNoqueos = goNoqueos.AddComponent<Outline>();
        outlineNoqueos.effectColor = Color.black;
        outlineNoqueos.effectDistance = new Vector2(1.5f, 1.5f);

        // 6. Texto de Anuncios Centrales
        GameObject goAnuncios = new GameObject("TextoAnuncios");
        goAnuncios.transform.SetParent(goCanvas.transform, false);
        textoAnuncios = goAnuncios.AddComponent<Text>();
        textoAnuncios.font = Resources.GetBuiltinResource<Font>("LegacyRuntime.ttf");
        textoAnuncios.fontSize = 52; // Un poco más grande para impacto visual
        textoAnuncios.alignment = TextAnchor.MiddleCenter;
        textoAnuncios.color = Color.yellow;
        textoAnuncios.gameObject.SetActive(false);
        
        RectTransform rtAnuncios = goAnuncios.GetComponent<RectTransform>();
        rtAnuncios.anchorMin = new Vector2(0.5f, 0.5f);
        rtAnuncios.anchorMax = new Vector2(0.5f, 0.5f);
        rtAnuncios.anchoredPosition = new Vector2(0f, 120f); // Posicionado arriba del centro
        rtAnuncios.sizeDelta = new Vector2(900f, 120f);

        Outline outlineAnuncios = goAnuncios.AddComponent<Outline>();
        outlineAnuncios.effectColor = Color.black;
        outlineAnuncios.effectDistance = new Vector2(3f, 3f);

        // 7. Panel de Fin de Partido (Fondo oscuro total a pantalla completa para enfocar atención)
        panelFinPartido = new GameObject("PanelFinPartido");
        panelFinPartido.transform.SetParent(goCanvas.transform, false);
        panelFinPartido.SetActive(false);
        
        RectTransform rtFin = panelFinPartido.AddComponent<RectTransform>();
        rtFin.anchorMin = new Vector2(0f, 0f);
        rtFin.anchorMax = new Vector2(1f, 1f);
        rtFin.pivot = new Vector2(0.5f, 0.5f);
        rtFin.anchoredPosition = Vector2.zero;
        rtFin.sizeDelta = Vector2.zero;
        
        Image imgFin = panelFinPartido.AddComponent<Image>();
        imgFin.color = new Color(0.02f, 0.02f, 0.04f, 0.8f); // Negro azulado traslúcido
        
        // Evita clics accidentales detrás del panel
        panelFinPartido.AddComponent<CanvasGroup>();

        // Tarjeta central de estadísticas (Stats Card)
        GameObject goCard = new GameObject("TarjetaEstadisticas");
        goCard.transform.SetParent(panelFinPartido.transform, false);
        
        RectTransform rtCard = goCard.AddComponent<RectTransform>();
        rtCard.anchorMin = new Vector2(0.5f, 0.5f);
        rtCard.anchorMax = new Vector2(0.5f, 0.5f);
        rtCard.pivot = new Vector2(0.5f, 0.5f);
        rtCard.anchoredPosition = Vector2.zero;
        rtCard.sizeDelta = new Vector2(580f, 500f);
        
        Image imgCard = goCard.AddComponent<Image>();
        imgCard.color = new Color(0.06f, 0.06f, 0.10f, 0.95f); // Gris azulado premium
        
        Outline outlineCard = goCard.AddComponent<Outline>();
        outlineCard.effectColor = new Color(1f, 0.84f, 0f, 0.75f); // Dorado brillante para la tarjeta de resumen
        outlineCard.effectDistance = new Vector2(3f, 3f);
        
        Shadow shadowCard = goCard.AddComponent<Shadow>();
        shadowCard.effectColor = new Color(0f, 0f, 0f, 0.6f);
        shadowCard.effectDistance = new Vector2(8f, -8f);

        // Título "RESUMEN DEL PARTIDO"
        GameObject goFinTitulo = new GameObject("FinTitulo");
        goFinTitulo.transform.SetParent(goCard.transform, false);
        Text txtFinTitulo = goFinTitulo.AddComponent<Text>();
        txtFinTitulo.font = Resources.GetBuiltinResource<Font>("LegacyRuntime.ttf");
        txtFinTitulo.fontSize = 36;
        txtFinTitulo.alignment = TextAnchor.MiddleCenter;
        txtFinTitulo.text = "RESUMEN DEL PARTIDO";
        txtFinTitulo.color = new Color(1f, 0.84f, 0f); // Dorado
        
        RectTransform rtFinTitulo = goFinTitulo.GetComponent<RectTransform>();
        rtFinTitulo.anchorMin = new Vector2(0.5f, 1f);
        rtFinTitulo.anchorMax = new Vector2(0.5f, 1f);
        rtFinTitulo.pivot = new Vector2(0.5f, 1f);
        rtFinTitulo.anchoredPosition = new Vector2(0f, -35f);
        rtFinTitulo.sizeDelta = new Vector2(500f, 50f);

        Outline outlineFinTitulo = goFinTitulo.AddComponent<Outline>();
        outlineFinTitulo.effectColor = Color.black;
        outlineFinTitulo.effectDistance = new Vector2(2f, 2f);

        // Texto Resumen Estadísticas
        GameObject goResumen = new GameObject("TextoResumen");
        goResumen.transform.SetParent(goCard.transform, false);
        textoResumenFin = goResumen.AddComponent<Text>();
        textoResumenFin.font = Resources.GetBuiltinResource<Font>("LegacyRuntime.ttf");
        textoResumenFin.fontSize = 22;
        textoResumenFin.alignment = TextAnchor.MiddleCenter;
        textoResumenFin.supportRichText = true;
        textoResumenFin.color = Color.white;
        
        RectTransform rtResumen = goResumen.GetComponent<RectTransform>();
        rtResumen.anchorMin = new Vector2(0.5f, 0.5f);
        rtResumen.anchorMax = new Vector2(0.5f, 0.5f);
        rtResumen.pivot = new Vector2(0.5f, 0.5f);
        rtResumen.anchoredPosition = new Vector2(0f, 0f);
        rtResumen.sizeDelta = new Vector2(500f, 260f);

        // Botón de Reiniciar (Jugar Otra Vez)
        GameObject goBoton = new GameObject("BotonReiniciar");
        goBoton.transform.SetParent(goCard.transform, false);
        
        RectTransform rtBoton = goBoton.AddComponent<RectTransform>();
        rtBoton.anchorMin = new Vector2(0.5f, 0f);
        rtBoton.anchorMax = new Vector2(0.5f, 0f);
        rtBoton.pivot = new Vector2(0.5f, 0f);
        rtBoton.anchoredPosition = new Vector2(-130f, 40f);
        rtBoton.sizeDelta = new Vector2(240f, 50f);
        
        Image imgBoton = goBoton.AddComponent<Image>();
        imgBoton.color = new Color(0.12f, 0.53f, 0.28f); // Verde
        
        Outline outlineBoton = goBoton.AddComponent<Outline>();
        outlineBoton.effectColor = new Color(0.5f, 1f, 0.6f, 0.4f);
        outlineBoton.effectDistance = new Vector2(1.5f, 1.5f);

        botonReiniciar = goBoton.AddComponent<Button>();
        
        // Transición de color del botón al pasar el mouse
        ColorBlock coloresBoton = botonReiniciar.colors;
        coloresBoton.normalColor = new Color(0.12f, 0.53f, 0.28f);
        coloresBoton.highlightedColor = new Color(0.18f, 0.7f, 0.38f);
        coloresBoton.pressedColor = new Color(0.08f, 0.38f, 0.2f);
        botonReiniciar.colors = coloresBoton;

        // Texto dentro del Botón
        GameObject goBotonTexto = new GameObject("TextoBoton");
        goBotonTexto.transform.SetParent(goBoton.transform, false);
        Text txtBoton = goBotonTexto.AddComponent<Text>();
        txtBoton.font = Resources.GetBuiltinResource<Font>("LegacyRuntime.ttf");
        txtBoton.fontSize = 18;
        txtBoton.alignment = TextAnchor.MiddleCenter;
        txtBoton.text = "🔄 JUGAR OTRA VEZ";
        txtBoton.color = Color.white;
        
        RectTransform rtBotonTexto = goBotonTexto.GetComponent<RectTransform>();
        rtBotonTexto.anchorMin = Vector2.zero;
        rtBotonTexto.anchorMax = Vector3.one;
        rtBotonTexto.sizeDelta = Vector2.zero;

        Outline outlineTxtBoton = goBotonTexto.AddComponent<Outline>();
        outlineTxtBoton.effectColor = Color.black;
        outlineTxtBoton.effectDistance = new Vector2(1.5f, 1.5f);

        // Añadir Listener para el reinicio
        botonReiniciar.onClick.AddListener(RecomenzarPartido);

        // Nuevo Botón de Salir del Juego
        GameObject goBotonSalir = new GameObject("BotonSalir");
        goBotonSalir.transform.SetParent(goCard.transform, false);
        
        RectTransform rtBotonSalir = goBotonSalir.AddComponent<RectTransform>();
        rtBotonSalir.anchorMin = new Vector2(0.5f, 0f);
        rtBotonSalir.anchorMax = new Vector2(0.5f, 0f);
        rtBotonSalir.pivot = new Vector2(0.5f, 0f);
        rtBotonSalir.anchoredPosition = new Vector2(130f, 40f);
        rtBotonSalir.sizeDelta = new Vector2(240f, 50f);
        
        Image imgBotonSalir = goBotonSalir.AddComponent<Image>();
        imgBotonSalir.color = new Color(0.6f, 0.2f, 0.2f); // Rojo
        
        Outline outlineBotonSalir = goBotonSalir.AddComponent<Outline>();
        outlineBotonSalir.effectColor = new Color(1f, 0.6f, 0.6f, 0.4f);
        outlineBotonSalir.effectDistance = new Vector2(1.5f, 1.5f);

        Button botonSalir = goBotonSalir.AddComponent<Button>();
        
        ColorBlock coloresBotonSalir = botonSalir.colors;
        coloresBotonSalir.normalColor = new Color(0.6f, 0.2f, 0.2f);
        coloresBotonSalir.highlightedColor = new Color(0.8f, 0.3f, 0.3f);
        coloresBotonSalir.pressedColor = new Color(0.4f, 0.15f, 0.15f);
        botonSalir.colors = coloresBotonSalir;

        // Texto dentro del Botón Salir
        GameObject goBotonSalirTexto = new GameObject("TextoBotonSalir");
        goBotonSalirTexto.transform.SetParent(goBotonSalir.transform, false);
        Text txtBotonSalir = goBotonSalirTexto.AddComponent<Text>();
        txtBotonSalir.font = Resources.GetBuiltinResource<Font>("LegacyRuntime.ttf");
        txtBotonSalir.fontSize = 18;
        txtBotonSalir.alignment = TextAnchor.MiddleCenter;
        txtBotonSalir.text = "❌ SALIR DEL JUEGO";
        txtBotonSalir.color = Color.white;
        
        RectTransform rtBotonSalirTexto = goBotonSalirTexto.GetComponent<RectTransform>();
        rtBotonSalirTexto.anchorMin = Vector2.zero;
        rtBotonSalirTexto.anchorMax = Vector3.one;
        rtBotonSalirTexto.sizeDelta = Vector2.zero;

        Outline outlineTxtBotonSalir = goBotonSalirTexto.AddComponent<Outline>();
        outlineTxtBotonSalir.effectColor = Color.black;
        outlineTxtBotonSalir.effectDistance = new Vector2(1.5f, 1.5f);

        // Añadir Listener para salir
        botonSalir.onClick.AddListener(SalirDelJuego);
    }
}
